//! Returns the dependency tree using the Cargo.lock file.

/// A single package node in the dependency tree.
#[derive(Debug)]
pub struct Package<'a> {
    /// The package name.
    pub name: &'a str,
    /// The package version.
    pub version: &'a str,
    /// Indices of this package's dependencies within [`DependencyTree::nodes`].
    pub dependencies: Vec<usize>,
}

/// A parsed Cargo.lock dependency tree.
#[derive(Debug)]
pub struct DependencyTree<'a> {
    /// All package nodes, indexed by position.
    pub nodes: Vec<Package<'a>>,
    /// Index of the root package (the crate itself) in `nodes`.
    pub root: usize,
}

/// Parses a Cargo.lock file's contents into a [`DependencyTree`].
///
/// Returns an empty tree (no nodes, root `0`) if no packages are found.
#[must_use]
pub fn dependency_tree(input: &str) -> DependencyTree<'_> {
    let packages: Vec<&str> =
        input.split("[[package]]").filter(|pkg| pkg.contains("name = ")).collect();
    let find_idx =
        // TODO: need to extract the version if the dependency is unambiguous
        |name: &str| packages.iter().position(|block| extract_val(block, "name = ") == Some(name));
    let nodes: Vec<Package> = packages
        .iter()
        .filter_map(|block| {
            let name = extract_val(block, "name = ")?;
            let version = extract_val(block, "version = ")?;
            let dependencies = extract_deps(block).into_iter().filter_map(find_idx).collect();
            Some(Package { name, version, dependencies })
        })
        .collect();

    // TODO: the root is not always in the first position, the packages are in abc order
    DependencyTree { nodes, root: 0 }
}

// TODO: return error if lockfile is invalid
fn extract_val<'a>(block: &'a str, key: &str) -> Option<&'a str> {
    block
        .lines()
        .map(str::trim)
        .find(|line| line.starts_with(key))
        .and_then(|line| line.split('"').nth(1))
}

fn extract_deps(block: &str) -> Vec<&str> {
    block
        .split_once("dependencies = [")
        .and_then(|(_, rest)| rest.split_once(']'))
        .map(|(deps_str, _)| deps_str.lines().filter_map(|line| line.split('"').nth(1)).collect())
        .unwrap_or_default()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn simple() {
        let input = r#"
        # This file is automatically @generated by Cargo.
        # It is not intended for manual editing.
        version = 4

        [[package]]
        name = "cargo-issafe"
        version = "0.3.0"
        dependencies = [
         "rustc_lexer",
        ]

        [[package]]
        name = "rustc_lexer"
        version = "0.1.0"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "c86aae0c77166108c01305ee1a36a1e77289d7dc6ca0a3cd91ff4992de2d16a5"
        dependencies = [
         "unicode-xid",
        ]

        [[package]]
        name = "unicode-xid"
        version = "0.2.6"
        source = "registry+https://github.com/rust-lang/crates.io-index"
        checksum = "ebc1c04c71510c7f702b52b7c350734c9ff1295c464a03335b00bb84fc54f853"
        "#;

        let tree = dependency_tree(input);
        println!("{tree:#?}");
    }

    #[test]
    fn complex() {
        let input = r#"
            # This file is automatically @generated by Cargo.
            # It is not intended for manual editing.
            version = 3

            [[package]]
            name = "arbitrary"
            version = "1.4.2"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "c3d036a3c4ab069c7b410a2ce876bd74808d2d0888a82667669f8e783a898bf1"
            dependencies = [
             "derive_arbitrary",
            ]

            [[package]]
            name = "bytemuck_derive"
            version = "1.12.1"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "6a1f896587b6f2c069c73d2f0913e2d590c3990285cd2f0b6aa02b786b4c679c"
            dependencies = [
             "proc-macro2",
             "quote",
             "syn 3.0.6",
            ]

            [[package]]
            name = "derive_arbitrary"
            version = "1.4.2"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "1e567bd82dcff979e4b03460c307b3cdc9e96fde3d73bed1496d2bc75d9dd62a"
            dependencies = [
             "proc-macro2",
             "quote",
             "syn 2.0.119",
            ]

            [[package]]
            name = "proc-macro2"
            version = "1.0.107"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "985e7ec9bb745e6ce6535b544d84d6cd6f7ad8bd711c398938ae983b91a766d9"
            dependencies = [
             "unicode-ident",
            ]

            [[package]]
            name = "quote"
            version = "1.0.47"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "1fbf4db142a473a8d80c26bbf18454ed458bf8d26c8219c331daecfdbd079001"
            dependencies = [
             "proc-macro2",
            ]

            [[package]]
            name = "serde_derive"
            version = "1.0.229"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "e7a5d71263a5a7d47b41f6b3f06ba276f10cc18b0931f1799f710578e2309348"
            dependencies = [
             "proc-macro2",
             "quote",
             "syn 3.0.6",
            ]

            [[package]]
            name = "syn"
            version = "2.0.119"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "872831b642d1a07999a962a351ed35b955ea2cfc8f3862091e2a240a84f17297"
            dependencies = [
             "proc-macro2",
             "quote",
             "unicode-ident",
            ]

            [[package]]
            name = "syn"
            version = "3.0.6"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "8593e8e72159ed2257d083c7a454a85cbf854f37a0966d8d483aff8c8a3ebcee"
            dependencies = [
             "proc-macro2",
             "quote",
             "unicode-ident",
            ]

            [[package]]
            name = "unicode-ident"
            version = "1.0.26"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "d245f478577f809a851594d02313b640fb437e0bb33866753cff937863096954"

            [[package]]
            name = "zerocopy-derive"
            version = "0.8.59"
            source = "registry+https://github.com/rust-lang/crates.io-index"
            checksum = "ac4f328cf2f05d084e496c3e9c3f33ed0a183656a16e1fcec4d464d8373aec82"
            dependencies = [
             "proc-macro2",
             "quote",
             "syn 2.0.119",
            ]
            "#;

        let tree = dependency_tree(input);
        println!("{tree:#?}");
    }
}
